# HTTP 80 端口重定向到 HTTPS
server {
    listen       80;
    listen       [::]:80;
    server_name  bzy.ai4mobi.com;

    # 所有请求重定向到 HTTPS
    return 301 https://$host$request_uri;
}

# HTTPS 443 端口
server {
    listen       443 ssl http2;
    listen       [::]:443 ssl http2;
    server_name  bzy.ai4mobi.com;
    root         /usr/share/nginx/html;

    # SSL 证书
    ssl_certificate "/octopus/ssl/bzy.ai4mobi.com.pem";
    ssl_certificate_key "/octopus/ssl/bzy.ai4mobi.com.key";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # 静态文件服务
    location / {
        root /octopus/web/dist;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        try_files $uri $uri/ /index.html;
    }

    # HTTP API 代理
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:8888;
    }

    # WebSocket 代理
    location /ws {
        proxy_pass http://127.0.0.1:5555;
        proxy_http_version 1.1;                   # WebSocket 需要 HTTP/1.1
        proxy_set_header Upgrade $http_upgrade;   # 升级头
        proxy_set_header Connection "Upgrade";    # 升级连接
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;                # 长连接防断
        proxy_send_timeout 86400s;
    }

    # 错误页面
    error_page 404 /404.html;
    location = /40x.html {}

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {}
}